/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _dsh_marketplace_dsh_market_marketplace_installPlugin_parameter_0$schema = z.string()
const _dsh_marketplace_dsh_market_marketplace_installPlugin_parameter_1$schema = z.string()
const _dsh_marketplace_dsh_market_marketplace_installPlugin_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'exitCode': z.number().readonly(),
  'stdout': z.string().readonly(),
  'stderr': z.string().readonly(),
  'restartRequired': z.boolean().readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
})])
const _dsh_marketplace_dsh_market_marketplace_list_result$schema = z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'plugins': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'fullName': z.string().readonly(),
  'description': z.string().readonly(),
  'descriptionZh': z.string().readonly().optional(),
  'tags': z.array(z.string()).readonly(),
  'language': z.string().readonly(),
  'stars': z.number().readonly(),
  'verified': z.boolean().readonly(),
  'install': z.object({
  'target': z.string().readonly(),
  'spec': z.string().readonly(),
  'command': z.string().readonly(),
}).readonly(),
  'repository': z.string().readonly(),
  'homepage': z.string().readonly(),
})).readonly(),
}).readonly(),
})

export const TYPERT = {
  package: '@dsh-marketplace/dsh-market',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@dsh-marketplace/dsh-market#marketplace/installPlugin',
      service: 'marketplace',
      namespace: 'marketplace',
      method: 'installPlugin',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'profile',
          wire: 'profile',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-marketplace/dsh-market#marketplace/installPlugin:profile',
            schema: _dsh_marketplace_dsh_market_marketplace_installPlugin_parameter_0$schema,
          },
        },
        {
          name: 'spec',
          wire: 'spec',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@dsh-marketplace/dsh-market#marketplace/installPlugin:spec',
            schema: _dsh_marketplace_dsh_market_marketplace_installPlugin_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-marketplace/dsh-market/types#MarketplaceInstallResult',
        schema: _dsh_marketplace_dsh_market_marketplace_installPlugin_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/dsh-marketplace/src/index.ts","line":91,"column":9},
    },
    {
      id: '@dsh-marketplace/dsh-market#marketplace/list',
      service: 'marketplace',
      namespace: 'marketplace',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@dsh-marketplace/dsh-market/types#MarketplaceListResult',
        schema: _dsh_marketplace_dsh_market_marketplace_list_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/dsh-marketplace/src/index.ts","line":78,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
