/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { MarketplaceInstallResult, MarketplaceListResult } from '@dsh-marketplace/dsh-market/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d61726b6574706c616365 {
    install: (profile: string, spec: string) => Promise<RemoteResult<MarketplaceInstallResult>>
    list: () => Promise<RemoteResult<MarketplaceListResult>>
  }
  interface TypertRemoteMap {
    'marketplace/install': (profile: string, spec: string) => Promise<RemoteResult<MarketplaceInstallResult>>
    'marketplace/list': () => Promise<RemoteResult<MarketplaceListResult>>
  }
  interface TypertRemoteNamespaceMap {
    'marketplace': TypertRemoteNamespace$6d61726b6574706c616365
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
